= Cocoa
triplem
2005-02-19
:jbake-type: post
:jbake-status: published
:jbake-tags: Apple, Cocoa, Mac OS X

I am a java programmer for the last 6 years. In this time, I programmed EJBs, Servlets a couple of specialized eCommerce frameworks like ATG and Intershop. In the current company I moved on to Swing and now I am in the position of a release-/build-engineer. Before my work with Java I was involved in some small projects using PERL and during my university time I had to do some basic programming in C++. Well I don't want to talk too much about my working life, if you are interested in this, please read my http://private.javafreedom.org/resume.pdf[resume]. I was also involved in some open source projects, like Depot at apache.org, and also wrote a couple of articles about Java and projects I did with Java (see the list of publications).

Since I bought my eMac, I wanted to write some code with and for it. I think that Cocoa is a pretty nice framework written in Objective-C. Therefor I will now learn this new language. I would like to write a small program with Cocoa for the management of diabetes mellitus, since I am a diabetic anyway. So, I now have a basic idea of what to write, now I have to learn this new framework and do a step back from a language of Java and get used to a C dialect. A good starting point for this seems to be http://cocoadevcentral.com/[CocoaDevCentral]. I will report back, if I have some more experiences and got the development started. BTW, I already coded some very small and simple Applescript programs, one of which you can find in my previous blogs. Now this is a little bit bigger and therefor I need another language. I am probably even coding this stuff using the Cocoa Java binding. Right now I am not really sure. So, let's see how this is going to work out.