= Fon.com
triplem
2006-08-07
:jbake-type: post
:jbake-status: published
:jbake-tags: Communities, WLan

Hello, now I am a FONero (http://fon.com/[fon.com]). I have installed a new AP in my Living room. There is some stuff missing in the documentation of the routers. I have ordered two BUFFALO WHR-G54S and tried to configure it correctly. One was running out of the Box, the other one have had obviously still the original Buffalo Firmware on it. Furthermore there is a problem, when the AP is not connected to a DHCP Router. This can be solved pretty easily, you can connect your Computer via the LAN-Interface of the Router and can connect directly to the WAN-Configuration (192.168.10.1). There you can configure a static IP for the connection to the Internet. Now it is running. But still, I have the problem, that I wanted to connect to the router also through the WAN interface. therefor you have to re-configure the file /etc/firewall.user and open the ports 22 (SSH) and 80 (HTTP) for the Network. By default you will see two lines in this file, which you have to un-comment, to open SSH, also you can then copy these lines and change the Port to 80, then HTTP is also accessible. This is only needed in networks, where the router is not connected directly to the Internet, like suggested from fon.com. To edit this file, you first have to delete the link to it and copy the original file from /rom/etc/. Take care, because you can misconfigure the IPTable-Rulez and get no more connect to the Router. The obvious solution for this kind of problem is to re-Flash the Firmware 🙂 BTW, to get connect to the router, you need to configure the password at the Router-Homepage at fon.com. You will get access to this page, as soon as your router connects to the Internet. It takes a little bit of time, to sync the router and the fon.com configuration. Greetz Markus