= Password Manager
triplem
2006-03-14
:jbake-type: post
:jbake-status: published
:jbake-tags: Apple, Linux

Hello, currently I am looking for a password manager. I have one on my linux box (http://oss.codepoet.no/revelation/[Revelation]) which does exactly what I need. Also I am using http://passwordsafe.sourceforge.net/[PasswordSafe] at work, where I have to use a windoze box. These two are pretty much interchangeable, because they can read/write the same dataformat. Now I am looking for a software, which reads the same format on the Palm OS. Also it would be possible to interchange the data through a secure communication, possibly this is a solution? I just found http://gnukeyring.sourceforge.net/[KeyRing for PalmOS], but this is not compatible. Are there any solutions for this kind of problem? I cannot believe this. BTW, I did not wrote an entry, that I bought a Palm TX. I have had to decide if I buy a Axim (Dell) or a Palm. My decision was a Palm because right now I have no windoze box at home, and I don't want to change this. Furthermore Palm is supported by evolution and gnome and right now there is no sync between evolution and windows mobile 5. Anyway, I still have the Password manager issue. Can anybody help me?