= Software Development in the 21st century
triplem
2013-05-12
:jbake-type: post
:jbake-status: published
:jbake-tags: Common

In earlier days http://sourceforge.net/[sourceforge] was THE development plattform for open source project. This has changed nowadays. SF.net has now been overcome by https://github.com/[github] and additional services. SF.net was still adding services like e.g. git repositories (http://sourceforge.net/apps/trac/sourceforge/wiki/Git) and additional apps like http://sourceforge.net/apps/trac/sourceforge/about[Trac] and stuff. Sourceforge is furthermore converting the whole infrastructure to the Apache Foundation under the name http://incubator.apache.org/allura/[Allura]. The whole world is going into cloud based services (this is especially true for software development services like e.g. bug tracker and source code management systems) and one of the formerly biggest ones is going to open source their whole stack. Quite interesting, don't you think? +
github.com is still very specialized on git repositories and also some more stuff like issue tracking and a wiki and also some static page stuff (http://pages.github.com/[pages.github.com]). But the real interesting stuff is the git repository stuff. Even though there are some competitors in this area (think: https://bitbucket.org/[bitbucket.org] from one of the great companies in the software development area (http://www.atlassian.com/[atlassian], which bougth bitbucket quite some time ago and also added git quite quickly), as well as http://gitorious.org/[gitorious], github is still the largets in this area. All added values like e.g. Continuous Integration tools (think: https://travis-ci.org/[travis-ci]) are using the interfaces github is offering (called service hooks) to integrate their services. And, I have to admit, these services are doing a great job with this, and even offer so called "badges" to integrate their services even further into the project home page at github. Very smart. The whole business is going into the direction of the old unix philosophy (doing one thing, but doing it very good). +
Basically the whole industry is going into the cloud business and github and cohorts are the expression of this. Earlier on one big service like sourceforge offered the whole stuff, nowadays it is several small companies doing the same in different entities. I really do like this. What are the services I do like really and I do use in my latest developments?

* http://github.com[github.com]
* http://travis-ci.org[travis-ci]
* http://coveralls.io[coveralls.io]
* http://gemnasium.org[gemnasium.org]

There is one more thing about these services, they do not offer these services for one language or environment, but for several languages and environments, like http://www.ruby-lang.org/[Ruby] or http://nodejs.org[javascript/nodejs]. This is rather interesting. Even though some (if not most) of these services are written in Ruby, they do offer their services to other languages as well. This means, that the whole community recognizes, that there is more then just one language. While open source communities like e.g. http://jboss.org[jboss] or http://apache.org[apache] are focused on one/some specific languages (in the beforementioned Projects it is mostly Java) these are staying this way, but are still opening up to the rest of the world (e.g. https://github.com/hornetq/hornetq[HornetMQ at github.com]. +
If you take a look on the nodejs modules, it is clear that smaller modules are more welcome in the community then larger ones (e.g. http://expressjs.com/[expressj] vs. http://geddyjs.org/[geddyjs]). This is a nice trend going back to the "small but good" design principle, which I definitly acclaim. Basically this is all about http://en.wikipedia.org/wiki/KISS_principle["KISS"], and, just to mention it again, my preferred linux distribution is also all about the same principle (http://www.archlinux.org[ArchLinux]). +
So having said all this (and I believe this developed into a small rant) I still believe in the KISS principle and I am very glad to develop software in the 21st century 😉 Furthermore I believe that this is also a principle which is represented by http://de.wikipedia.org/wiki/Robert_Cecil_Martin[Uncle Bob] and his http://manifesto.softwarecraftsmanship.org/[Manifesto for Software Craftsmanship]. +
I hope, that I follow the above mentioned principle in the following new projects, I just published to github and the https://npmjs.org/[npmjs.org]:

* https://npmjs.org/package/winston-config[winston-config]
* https://npmjs.org/package/mongoskin-slug[mongoskin-slug]

What does this mean for us Developers? Basically I strongly believe, that Software Development in the future is more like building a castle with already existing lego blocks with the design of some Architect and the business logic concepts of some Product Owner. All we have to do is using the right tools for the right job (the selection is up to us fortunately) and implement the business logic with the right algorithms. This sounds like a abasement, but I do strongly believe that we are still Craftsman and can do a fine job on this one. It would be a decision, if we need an Architect, but the business logic should (at least IMHO) be designed by the guys and gals who know this better (Product Owner should know this better).